(()=>{
'use strict';
const SKINS=[
 ['gunmetal','Gun Metal',0,'skin-gunmetal.jpg',false],['hazard','Hazard Tape',5000,'skin-hazard.jpg',false],['neon','Neon Rogue',10000,'skin-neon.jpg',false],['jacko','Jack-o-Gun',15000,'skin-jacko.jpg',false],['milspec','MilSpec',25000,'skin-milspec.jpg',false],['arcade','Arcade Blast',40000,'skin-arcade.jpg',false],['blood','Blood Steel',60000,'skin-blood.jpg',false],['toxic','Toxic Slime',85000,'skin-toxic.jpg',false],['gold','Gold Ops',120000,'skin-gold.jpg',false],['founders','Founder Black',175000,'skin-founders.jpg',false],['phantom','PHANTOM ELITE',2000000000,'skin-phantom.jpg',true]
].map(([id,name,unlock,img,codeOnly])=>({id,name,unlock,img,codeOnly}));
const WEAPONS={pistol:{name:'PISTOL',ammo:Infinity,damage:1,delay:.30,speed:720},smg:{name:'SMG',ammo:48,damage:1,delay:.105,speed:800},dmr:{name:'DMR-82',ammo:8,damage:99,delay:.48,speed:940}};
const MAPS=[
 {id:'concrete',name:'THE GROUND',img:'map-concrete.jpg'},
 {id:'desert',name:'DESERT DUST',img:'map-desert.jpg'},
 {id:'north',name:'NORTH ASSAULT',img:'map-north.jpg'},
 {id:'hangar',name:'HANGAR',img:'map-hangar.jpg'},
 {id:'wasteland',name:'WASTELAND',img:'map-wasteland.jpg'}
];
const SPRITES={
 player:'player-transparent.png',normal:'zombie-normal.png',helmet:'zombie-helmet.png',fast:'zombie-fast.png',brute3:'zombie-brute-3.png',brute2:'zombie-brute-2.png',brute1:'zombie-brute-1.png'
};
let deps={};
let A={prefs:null,open:false,menu:false,tab:'menu',paused:false,engine:null,board:[],loading:false,images:{},audio:null,cheat:null,joystick:{active:false,pointer:null,x:0,y:0},adminAtOpen:false};
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const state=()=>deps.getState?.()||{}; const icon=n=>deps.icon?deps.icon(n):n; const esc=v=>deps.esc?deps.esc(v):String(v||''); const toast=m=>deps.setToast?.(m);
const skin=id=>SKINS.find(s=>s.id===id)||SKINS[0];
function init(d){deps=d;loadPrefs();preload();resetCheat();window.addEventListener('resize',()=>{if(A.open){resizeCanvas();draw();}});document.addEventListener('dblclick',blockZoom,{passive:false});document.addEventListener('gesturestart',blockZoom,{passive:false});}
function blockZoom(e){if(A.open){e.preventDefault();e.stopPropagation();}}
function loadPrefs(){let p={};try{p=JSON.parse(localStorage.getItem('zc2-zs-v53')||'{}')}catch{}A.prefs={skin:p.skin||'gunmetal',high:Number(p.high||0),last:Number(p.last||0),music:p.music!==false,flip:!!p.flip,control:'buttons',codeSkins:Array.isArray(p.codeSkins)?p.codeSkins:[]};if(!isUnlocked(A.prefs.skin))A.prefs.skin='gunmetal';}
function savePrefs(){localStorage.setItem('zc2-zs-v53',JSON.stringify(A.prefs));}
function adminUnlocked(){return !!state().admin;}
function isUnlocked(id){const s=skin(id);return id==='gunmetal'||adminUnlocked()||A.prefs.high>=s.unlock||A.prefs.codeSkins.includes(id);}
function preload(){Object.entries(SPRITES).forEach(([k,src])=>{const im=new Image();im.src='./'+src;A.images[k]=im;});}
function resetCheat(){A.cheat={dmrPhase:0,musicCount:0,dmrArmed:false,lifeFlipCount:0,lifeSawInstructions:false,lifeArmed:false};}
async function syncProfile(){if(!state().session)return;try{const {data}=await deps.supabase.from('arcade_profiles').select('high_score,selected_skin,unlocked_skins').eq('user_id',state().session.user.id).maybeSingle();if(!data)return;A.prefs.high=Math.max(A.prefs.high,Number(data.high_score||0));A.prefs.codeSkins=[...new Set([...(A.prefs.codeSkins||[]),...(data.unlocked_skins||[])])];if(data.selected_skin&&isUnlocked(data.selected_skin))A.prefs.skin=data.selected_skin;savePrefs();}catch(e){console.warn(e)}}
function pageHtml(){const top=A.board.slice(0,10);const cards=SKINS.slice(0,6).concat([skin('phantom')]).map(s=>`<article class="zs52-skin ${isUnlocked(s.id)?'':'locked'} ${s.codeOnly?'elite':''}"><img src="./${s.img}" alt="${esc(s.name)}"><div><b>${esc(s.name)}</b><small>${isUnlocked(s.id)?'UNLOCKED':s.codeOnly?'SPECIAL CODE ONLY':'Unlock '+s.unlock.toLocaleString()}</small></div></article>`).join('');return `<section class="zs52-hub"><div class="section-title"><span class="kicker">ARCADE</span><h2>ZC2 Arena: Zombie Smash</h2><p>Portrait horde defence with a fixed firing lane, tactile three-button controls, clean changing ground textures and a competitive all-time leaderboard.</p></div><div class="zs52-hero"><img src="./zc2-zombie-smash-promo.png" alt="Zombie Smash"><div><span class="live-pill"><i></i>HORDE DEFENCE</span><h1>DEFEND THE BASE.<br><em>BEAT THE BOARD.</em></h1><p>Zombies descend from the top of the battlefield. Stop the horde before too many reach the camp, collect rare weapons and power-ups, and survive progressively heavier waves.</p><div class="hero-stats"><span><b>${A.prefs.high.toLocaleString()}</b> personal best</span><span><b>10</b> breach limit</span><span><b>5</b> rotating grounds</span></div><div class="action-row"><button class="btn primary big" id="zs52Play">${icon('sports_esports')}Play Zombie Smash</button><button class="btn glass big" id="zs52BoardJump">${icon('leaderboard')}Leaderboard</button></div></div></div><div class="zs52-grid"><article class="panel premium-panel"><div class="panel-head"><div><span class="kicker">HORDE RULES</span><h2>Defend the line</h2></div></div><div class="zs52-rules"><div>${icon('south')}<span><b>Downward horde</b>Zombies steadily cross the map toward your camp.</span></div><div>${icon('shield')}<span><b>10 breaches</b>Let too many through and the base is overrun.</span></div><div>${icon('sports_esports')}<span><b>Left / right soldier</b>The soldier stays on the defence line and moves horizontally only.</span></div><div>${icon('ads_click')}<span><b>Straight fire</b>Tap or hold FIRE. Shots travel directly forward; there is no auto-aim.</span></div><div>${icon('map')}<span><b>Changing ground</b>Each horde cycle changes the clean ground texture without scenery hiding enemies.</span></div></div></article><article class="panel premium-panel"><div class="panel-head"><div><span class="kicker">CONSOLE SKINS</span><h2>Rendered shells</h2></div></div><div class="zs52-skin-grid">${cards}</div></article><article class="panel premium-panel" id="zs52BoardPanel"><div class="panel-head"><div><span class="kicker">ALL-TIME</span><h2>Community high scores</h2></div><button id="zs52Refresh">Refresh ›</button></div><div id="zs52Board">${boardRows(top)}</div></article></div></section>`}
function boardRows(rows){return rows?.length?rows.map((r,i)=>`<div class="rank-row"><span class="place">${r.rank||i+1}</span><span class="name">${esc(r.gamertag||'Player')}</span><span class="metric">${Number(r.high_score||0).toLocaleString()}</span><small>${esc(skin(r.selected_skin||'gunmetal').name)}</small></div>`).join(''):`<div class="empty"><div>${icon('leaderboard')}<div>No score posted yet.</div></div></div>`}
async function loadBoard(){if(A.loading)return;A.loading=true;try{let rows=[];const rpc=await deps.supabase.rpc('get_arcade_leaderboard',{p_limit:100});if(!rpc.error&&Array.isArray(rpc.data))rows=rpc.data;if(!rows.length){const {data,error}=await deps.supabase.from('arcade_profiles').select('user_id,high_score,selected_skin');if(error)throw error;const ps=state().profiles||[];rows=(data||[]).map(r=>({user_id:r.user_id,gamertag:ps.find(p=>p.id===r.user_id)?.gamertag||'Player',high_score:r.high_score||0,selected_skin:r.selected_skin||'gunmetal'})).sort((a,b)=>Number(b.high_score)-Number(a.high_score));}A.board=rows.map((r,i)=>({...r,rank:i+1}));}catch(e){console.warn('Arcade leaderboard:',e)}finally{A.loading=false;const el=$('#zs52Board');if(el)el.innerHTML=boardRows(A.board.slice(0,20));}}
function bindPage(){$('#zs52Play')?.addEventListener('click',open);$('#zs52Refresh')?.addEventListener('click',loadBoard);$('#zs52BoardJump')?.addEventListener('click',()=>$('#zs52BoardPanel')?.scrollIntoView({behavior:'smooth'}));syncProfile();loadBoard();}
async function open(){await syncProfile();A.adminAtOpen=adminUnlocked();A.open=true;A.menu=false;A.paused=false;document.documentElement.classList.add('zs52-locked');document.body.classList.add('zs52-playing');try{await screen.orientation?.lock?.('portrait')}catch{}try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen()}catch{}newRun();renderOverlay();}
function close(){stop();A.open=false;A.menu=false;document.documentElement.classList.remove('zs52-locked');document.body.classList.remove('zs52-playing');try{screen.orientation?.unlock?.()}catch{}try{if(document.fullscreenElement)document.exitFullscreen?.()}catch{}$('#zs52Root')?.remove();}
function newRun(){resetCheat();A.engine={canvas:null,ctx:null,w:0,h:0,last:0,raf:0,started:false,over:false,elapsed:0,wave:1,mapIndex:0,mapBanner:2.2,between:0,waveTarget:10,waveSpawned:0,waveResolved:0,spawnTimer:.5,pickupTimer:7,breaches:0,breachLimit:10,score:0,kills:0,slowUntil:0,speedUntil:0,rapidUntil:0,shieldUntil:0,ticker:'Press LEFT, RIGHT or FIRE to start',bullets:[],zombies:[],pickups:[],player:{x:0,y:0,r:18,lives:5,maxLives:5,inv:0,move:{x:0,y:0},gun:'pistol',ammo:Infinity,cool:0},fireHeld:false,cheated:false,cheats:{dmr:false,tenLives:false}};}
function renderOverlay(){let r=$('#zs52Root');if(!r){r=document.createElement('div');r.id='zs52Root';document.body.appendChild(r)}if(innerWidth>innerHeight){r.innerHTML=`<div class="zs52-overlay"><div class="zs52-portrait-warning"><img src="./community-arena-emblem.png" alt=""><span class="kicker">ZC2 ARENA</span><h2>Keep it portrait</h2><p>Zombie Smash is built as a tall handheld console. Rotate your device upright to play.</p><button class="btn primary big" id="zs52PortraitExit">Exit game</button></div></div>`;$('#zs52PortraitExit').onclick=close;return}r.innerHTML=consoleHtml();bindOverlay();resizeCanvas();draw();hud();}
function consoleHtml(){const s=skin(A.prefs.skin);return `<div class="zs52-overlay"><div class="zs52-shell skin-${s.id}" style="--skin-art:url('./${s.img}')"><div class="zs52-skinwash"></div><div class="zs52-screen"><div class="zs52-hudtop"><span><small>WAVE</small><b id="zs52Wave">1</b></span><span><small>ZOMBIES</small><b id="zs52Remaining">10</b></span><span><small>SCORE</small><b id="zs52Score">0</b></span><span><small>BASE</small><b id="zs52Base">0/10</b></span></div><canvas id="zs52Canvas"></canvas><div class="zs52-hudbottom"><div id="zs52Lives" class="zs52-lives"></div><div><small>WEAPON</small><b id="zs52Gun">PISTOL</b><span id="zs52Ammo">∞</span></div><div><small>GROUND</small><b id="zs52Map">CONCRETE</b></div></div><div id="zs52WaveBanner" class="zs52-wave-banner"></div></div><button class="zs52-topbtn menu" id="zs52Menu">${icon('menu')}<span>MENU</span></button><button class="zs52-topbtn pause" id="zs52Pause">${icon('pause')}<span>PAUSE</span></button><div class="zs52-move-zone ${A.prefs.flip?'flipped':''}"><span>MOVE</span><div class="zs52-lr"><button data-dir="left" class="left" aria-label="Move left"><b>◀</b><small>LEFT</small></button><button data-dir="right" class="right" aria-label="Move right"><b>▶</b><small>RIGHT</small></button></div></div><button class="zs52-fire ${A.prefs.flip?'flipped':''}" id="zs52Fire"><span class="zs52-fire-glow"></span>${icon('local_fire_department')}<b>FIRE</b><small>TAP / HOLD</small></button><button class="zs52-exit" id="zs52Exit">${icon('close')}</button><div class="zs52-ticker" id="zs52Ticker">${esc(A.engine?.ticker||'')}</div>${A.menu?menuHtml():''}</div></div>`}
function dpadHtml(){return ''}
function joystickHtml(){return ''}
function menuHtml(){const skins=SKINS.map(s=>`<button class="zs52-menu-skin ${isUnlocked(s.id)?'':'locked'} ${A.prefs.skin===s.id?'active':''} ${s.codeOnly?'elite':''}" data-skin="${s.id}" ${isUnlocked(s.id)?'':'disabled'}><img src="./${s.img}" alt=""><span><b>${esc(s.name)}</b><small>${isUnlocked(s.id)?(adminUnlocked()&&A.prefs.high<s.unlock&&!A.prefs.codeSkins.includes(s.id)?'ADMIN ACCESS':'UNLOCKED'):s.codeOnly?'SPECIAL CODE ONLY':'Unlock '+s.unlock.toLocaleString()}</small></span></button>`).join('');let body='';if(A.tab==='instructions')body=`<div class="zs52-instructions"><article><b>Defend the camp</b><span>Zombies move down from the top. Ten breaches ends the run.</span></article><article><b>Movement</b><span>Hold LEFT or RIGHT. The soldier stays on the defence line; there is no vertical movement.</span></article><article><b>Fire</b><span>Tap or hold FIRE. Every shot travels straight ahead from the soldier. Line yourself up with the target.</span></article><article><b>Zombie armour</b><span>Most walkers are one shot. Helmet walkers take two shots and visibly lose the helmet. Brutes take three.</span></article><article><b>Power-ups</b><span>Pick-ups appear directly on your movement line: speed boost, rapid fire, shield, hearts, slow-time, bomb, SMG and DMR-82.</span></article></div>`;else if(A.tab==='leaderboard')body=`<div class="zs52-menu-board">${boardRows(A.board.slice(0,25))}</div>`;else if(A.tab==='skins')body=`<div class="zs52-code"><input id="zs52SkinCode" maxlength="4" inputmode="numeric" placeholder="4-digit skin code"><button class="btn primary" id="zs52Redeem">Unlock</button><small>Skin codes do not grant admin access.</small></div><div class="zs52-menu-skins">${skins}</div>`;else body=`<div class="zs52-menu-actions"><button class="btn primary big" id="zs52Resume">${icon('play_arrow')}Resume</button><button class="btn secondary big" id="zs52Flip">${icon('swap_horiz')}Swap sides: ${A.prefs.flip?'ON':'OFF'}</button><button class="btn secondary big" id="zs52Music">${icon(A.prefs.music?'volume_up':'volume_off')}Sound: ${A.prefs.music?'ON':'OFF'}</button><button class="btn danger big" id="zs52Quit">${icon('logout')}Exit to app</button></div>`;return `<div class="zs52-menu-layer"><div class="zs52-menu-box"><header><div><span class="kicker">ZC2 ARENA</span><h2>Zombie Smash</h2></div><button id="zs52MenuClose">${icon('close')}</button></header><nav>${['menu','instructions','leaderboard','skins'].map(t=>`<button data-tab="${t}" class="${A.tab===t?'active':''}">${t}</button>`).join('')}</nav>${body}</div></div>`}
function bindOverlay(){$('#zs52Exit')?.addEventListener('click',close);$('#zs52Menu')?.addEventListener('click',openMenu);$('#zs52Pause')?.addEventListener('click',togglePause);$('#zs52MenuClose')?.addEventListener('click',closeMenu);$('#zs52Resume')?.addEventListener('click',closeMenu);$('#zs52Quit')?.addEventListener('click',close);$('#zs52Flip')?.addEventListener('click',toggleFlip);$('#zs52Music')?.addEventListener('click',toggleMusic);$('#zs52Redeem')?.addEventListener('click',redeemCode);$$('[data-tab]').forEach(b=>b.onclick=()=>{A.tab=b.dataset.tab;if(A.tab==='instructions'&&!A.engine.started)A.cheat.lifeSawInstructions=true;renderOverlay()});$$('[data-skin]').forEach(b=>b.onclick=()=>selectSkin(b.dataset.skin));bindMovement();const f=$('#zs52Fire');if(f){const on=e=>{e.preventDefault();startGameIfNeeded();A.engine.fireHeld=true;shoot(true);f.classList.add('pressed')};const off=e=>{e?.preventDefault?.();if(A.engine)A.engine.fireHeld=false;f.classList.remove('pressed')};f.addEventListener('pointerdown',on);f.addEventListener('pointerup',off);f.addEventListener('pointercancel',off);f.addEventListener('pointerleave',off)} }
function bindMovement(){
  $$('[data-dir]').forEach(b=>{const d=b.dataset.dir;const on=e=>{e.preventDefault();startGameIfNeeded();A.engine.player.move={x:d==='left'?-1:1,y:0};b.classList.add('pressed');try{b.setPointerCapture?.(e.pointerId)}catch{}};const off=e=>{e?.preventDefault?.();if(A.engine)A.engine.player.move={x:0,y:0};b.classList.remove('pressed')};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('lostpointercapture',off)});
}
function openMenu(){A.menu=true;A.paused=true;stopLoop();renderOverlay()}
function closeMenu(){if(!A.engine.started&&A.cheat.dmrPhase===1&&A.cheat.musicCount>=6){A.cheat.dmrPhase=2;A.cheat.musicCount=0}if(!A.engine.started&&A.cheat.lifeFlipCount>=5&&A.cheat.lifeSawInstructions)A.cheat.lifeArmed=true;A.menu=false;A.paused=false;renderOverlay();startLoop()}
function togglePause(){A.paused=!A.paused;if(A.paused)stopLoop();else startLoop();hud()}
function toggleFlip(){A.prefs.flip=!A.prefs.flip;savePrefs();if(!A.engine.started)A.cheat.lifeFlipCount++;renderOverlay()}
function toggleMusic(){A.prefs.music=!A.prefs.music;savePrefs();if(!A.engine.started){A.cheat.musicCount++;if(A.cheat.dmrPhase===0&&A.cheat.musicCount>=6){A.cheat.dmrPhase=1;A.cheat.musicCount=6}else if(A.cheat.dmrPhase===2&&A.cheat.musicCount>=6)A.cheat.dmrArmed=true}A.prefs.music?startMusic():stopMusic();renderOverlay()}
async function redeemCode(){const code=$('#zs52SkinCode')?.value.trim();if(!/^\d{4}$/.test(code||''))return toast('Enter a 4-digit skin code.');try{const {data,error}=await deps.supabase.rpc('redeem_arcade_skin_code',{p_code:code});if(error)throw error;if(!data)return toast('Code not recognised.');A.prefs.codeSkins=[...new Set([...(A.prefs.codeSkins||[]),data])];A.prefs.skin=data;savePrefs();toast(`${skin(data).name} unlocked.`);renderOverlay()}catch(e){toast(state().session?'Code could not be redeemed.':'Sign in to redeem skin codes.')}}
async function selectSkin(id){if(!isUnlocked(id))return;A.prefs.skin=id;savePrefs();if(state().session)deps.supabase.rpc('set_arcade_skin',{p_skin:id}).catch(()=>{});renderOverlay()}
function startGameIfNeeded(){if(!A.engine||A.engine.started)return;applyCheats();A.engine.started=true;A.engine.ticker=A.engine.cheated?'CHEAT RUN · LEADERBOARD DISABLED':'Wave 1 incoming';startLoop()}
function applyCheats(){const e=A.engine;if(A.cheat.dmrArmed){e.cheated=true;e.cheats.dmr=true;e.player.gun='dmr';e.player.ammo=Infinity}if(A.cheat.lifeArmed){e.cheated=true;e.cheats.tenLives=true;e.player.maxLives=10;e.player.lives=10}hud()}
function resizeCanvas(){const c=$('#zs52Canvas'),e=A.engine;if(!c||!e)return;const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));e.ctx=c.getContext('2d');e.w=r.width;e.h=r.height;if(!e.player.x){e.player.x=e.w*.5;e.player.y=e.h*.84}else{e.player.y=e.h*.84}e.canvas=c}
function startLoop(){if(!A.open||A.paused||A.menu||!A.engine)return;stopLoop();const loop=ts=>{const e=A.engine;if(!A.open||A.paused||A.menu||e.over)return;if(!e.last)e.last=ts;const dt=Math.min(.033,(ts-e.last)/1000||.016);e.last=ts;update(dt);draw();hud();e.raf=requestAnimationFrame(loop)};A.engine.raf=requestAnimationFrame(loop);if(A.prefs.music)startMusic()}
function stopLoop(){if(A.engine?.raf)cancelAnimationFrame(A.engine.raf);if(A.engine)A.engine.raf=0}
function stop(){stopLoop();stopMusic()}
function waveCount(w){return Math.min(54,8+w*2+Math.floor(w/4)*2)}
function startNextWave(){const e=A.engine;e.wave++;e.mapIndex=Math.floor((e.wave-1)/3)%MAPS.length;e.waveTarget=waveCount(e.wave);e.waveSpawned=0;e.waveResolved=0;e.spawnTimer=.8;e.between=0;e.mapBanner=2.1;e.ticker=`Wave ${e.wave} · ${MAPS[e.mapIndex].name}`}
function update(dt){const e=A.engine;if(!e||e.over||!e.started)return;e.elapsed+=dt;const p=e.player,pSpeed=88*(e.elapsed<e.speedUntil?1.85:1);p.x+=p.move.x*pSpeed*dt;p.x=Math.max(22,Math.min(e.w-22,p.x));p.y=e.h*.84;p.inv=Math.max(0,p.inv-dt);p.cool=Math.max(0,p.cool-dt);if(e.fireHeld)shoot(false);if(e.mapBanner>0)e.mapBanner-=dt;if(e.between>0){e.between-=dt;if(e.between<=0)startNextWave();return}e.spawnTimer-=dt;const liveCap=Math.min(22,7+Math.floor(e.wave*.8));if(e.waveSpawned<e.waveTarget&&e.spawnTimer<=0&&e.zombies.length<liveCap){spawnZombie();e.waveSpawned++;e.spawnTimer=Math.max(.62,1.55-e.wave*.045)+Math.random()*.2}e.pickupTimer-=dt;if(e.pickupTimer<=0){spawnPickup(false);e.pickupTimer=9+Math.random()*5;}for(const b of e.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt}e.bullets=e.bullets.filter(b=>b.life>0&&b.x>-20&&b.x<e.w+20&&b.y>-20&&b.y<e.h+20);const slowZ=e.elapsed<e.slowUntil?.45:1;for(const z of e.zombies){z.flash=Math.max(0,z.flash-dt);if(z.dead){z.death=(z.death||0)-dt;continue}if(z.type==='brute'){const dx=p.x-z.x,dy=p.y-z.y,l=Math.hypot(dx,dy)||1;z.x+=dx/l*z.speed*slowZ*dt;z.y+=dy/l*z.speed*slowZ*dt}else z.y+=z.speed*slowZ*dt;if(Math.hypot(z.x-p.x,z.y-p.y)<z.r+p.r&&p.inv<=0&&e.elapsed>=e.shieldUntil){p.lives--;p.inv=1.5;e.ticker='Hit! Keep defending.';fx(110,.10);if(p.lives<=0)return gameOver('The soldier went down.')}if(z.y>e.h+30){z.dead=true;e.breaches++;e.waveResolved++;e.ticker=`Base breach ${e.breaches}/${e.breachLimit}`;if(e.breaches>=e.breachLimit)return gameOver('The camp was overrun.')}}for(const b of e.bullets){for(const z of e.zombies){if(z.dead)continue;if(Math.hypot(b.x-z.x,b.y-z.y)<z.r+5){z.hp-=b.damage;b.life=0;z.flash=.12;if(z.hp<=0){z.dead=true;z.death=.085;z.flash=.085;e.kills++;e.waveResolved++;e.score+=z.points;if(e.score>A.prefs.high){A.prefs.high=e.score;savePrefs()}if(Math.random()<.075)spawnPickup(true);fx(520,.03)}break}}}e.zombies=e.zombies.filter(z=>!z.dead||(z.death||0)>0);for(const x of e.pickups){x.life-=dt;x.blink=x.life<2.3&&Math.floor(x.life*7)%2===0;if(Math.hypot(x.x-p.x,x.y-p.y)<x.r+p.r){applyPickup(x);x.life=0}}e.pickups=e.pickups.filter(x=>x.life>0);if(e.waveSpawned>=e.waveTarget&&e.zombies.length===0&&e.waveResolved>=e.waveTarget){e.between=2.3;e.ticker=`Wave ${e.wave} cleared`;e.mapBanner=2.3}}
function spawnZombie(){const e=A.engine;const x=30+Math.random()*(e.w-60),r=Math.random();let type='normal';if(e.wave>=3&&r>.92)type='fast';if(e.wave>=5&&r>.965)type='brute';if(type==='normal'&&Math.random()<.46)type='helmet';const baseSpeed=18+Math.min(18,e.wave*.8);let hp=1,points=100,speed=baseSpeed,radius=16;if(type==='helmet'){hp=2;points=165;speed=baseSpeed*.93}if(type==='fast'){hp=1;points=220;speed=baseSpeed*1.65;radius=15}if(type==='brute'){hp=3;points=450;speed=baseSpeed*.52;radius=28}e.zombies.push({x,y:-35,type,hp,maxHp:hp,points,speed,r:radius,flash:0,dead:false})}
function shoot(force){const e=A.engine,p=e?.player;if(!e||!p||(!force&&p.cool>0))return;const w=WEAPONS[p.gun];if(p.gun!=='pistol'&&!e.cheats.dmr&&p.ammo<=0){setGun('pistol');return}const dx=0,dy=-1;e.bullets.push({x:p.x,y:p.y-25,vx:0,vy:-w.speed,damage:w.damage,life:1.45,color:p.gun==='dmr'?'#f6d84a':p.gun==='smg'?'#75e8ff':'#fff4d0'});p.cool=e.elapsed<e.rapidUntil?Math.max(.055,w.delay*.48):w.delay;if(p.gun!=='pistol'&&!e.cheats.dmr){p.ammo--;if(p.ammo<=0)setTimeout(()=>setGun('pistol'),20)}fx(p.gun==='dmr'?170:p.gun==='smg'?340:280,p.gun==='dmr'?.07:.025)}
function spawnPickup(fromKill=false){const e=A.engine;const types=['heart','clock','bomb','smg','dmr','speed','rapid','shield'];const type=types[Math.floor(Math.random()*types.length)];const y=e.player.y;e.pickups.push({x:28+Math.random()*(e.w-56),y,type,life:fromKill?6.5:9,r:15,blink:false})}
function applyPickup(x){const e=A.engine,p=e.player;if(x.type==='heart')p.lives=Math.min(p.maxLives,p.lives+1);if(x.type==='clock')e.slowUntil=e.elapsed+6;if(x.type==='speed')e.speedUntil=e.elapsed+7;if(x.type==='rapid')e.rapidUntil=e.elapsed+7;if(x.type==='shield')e.shieldUntil=e.elapsed+7;if(x.type==='bomb'){for(const z of e.zombies){if(!z.dead){z.dead=true;e.score+=z.points;e.kills++;e.waveResolved++}}e.zombies=[]}if(x.type==='smg'&&!e.cheats.dmr)setGun('smg');if(x.type==='dmr'&&!e.cheats.dmr)setGun('dmr');e.ticker={heart:'+1 life',clock:'Slow-time active',bomb:'Bomb cleared the horde',smg:'SMG collected',dmr:'DMR-82 collected',speed:'FAST MOVE · 7 seconds',rapid:'RAPID FIRE · 7 seconds',shield:'SHIELD · 7 seconds'}[x.type];fx(720,.06)}
function setGun(g){const e=A.engine,p=e.player;if(e.cheats.dmr){p.gun='dmr';p.ammo=Infinity;return}p.gun=g;p.ammo=WEAPONS[g].ammo}
function currentSprite(z){if(z.type==='helmet')return z.hp>=2?'helmet':'normal';if(z.type==='fast')return'fast';if(z.type==='brute')return z.hp>=3?'brute3':z.hp===2?'brute2':'brute1';return'normal'}
function draw(){const e=A.engine,c=e?.ctx;if(!e||!c)return;const d=Math.min(devicePixelRatio||1,2);c.setTransform(d,0,0,d,0,0);drawGround(c,e);for(const x of e.pickups)drawPickup(c,x);for(const b of e.bullets){c.fillStyle=b.color;c.beginPath();c.arc(b.x,b.y,3.5,0,Math.PI*2);c.fill()}for(const z of e.zombies){const im=A.images[currentSprite(z)];c.save();if(z.dead){c.globalAlpha=.75;c.filter='brightness(2.2) saturate(.2)'}else if(z.flash)c.globalAlpha=.62;const sw=z.type==='brute'?70:50,sh=z.type==='brute'?84:64;if(im?.complete)c.drawImage(im,z.x-sw/2,z.y-sh/2,sw,sh);else{c.fillStyle='#8b2d28';c.beginPath();c.arc(z.x,z.y,z.r,0,Math.PI*2);c.fill()}c.restore();const bw=z.type==='brute'?56:38,bh=4,x=z.x-bw/2,y=z.y-(z.type==='brute'?48:35);c.fillStyle='rgba(0,0,0,.7)';c.fillRect(x,y,bw,bh);c.fillStyle=z.hp/z.maxHp>.66?'#79c65c':z.hp/z.maxHp>.33?'#f0b63c':'#e44b3f';c.fillRect(x+1,y+1,(bw-2)*(z.hp/z.maxHp),bh-2)}const p=e.player,pi=A.images.player;c.save();if(p.inv&&Math.floor(p.inv*10)%2===0)c.globalAlpha=.35;if(e.elapsed<e.shieldUntil){c.strokeStyle='rgba(98,211,255,.9)';c.lineWidth=3;c.shadowBlur=15;c.shadowColor='#62d3ff';c.beginPath();c.arc(p.x,p.y-1,31,0,Math.PI*2);c.stroke();c.shadowBlur=0}if(pi?.complete)c.drawImage(pi,p.x-25,p.y-32,50,64);else{c.fillStyle='#7ed3ff';c.beginPath();c.arc(p.x,p.y,18,0,Math.PI*2);c.fill()}c.restore();c.strokeStyle='rgba(245,215,29,.24)';c.lineWidth=1;c.setLineDash([7,8]);c.beginPath();c.moveTo(16,p.y+32);c.lineTo(e.w-16,p.y+32);c.stroke();c.setLineDash([]);c.fillStyle='rgba(18,22,24,.7)';c.fillRect(0,e.h-7,e.w,7);c.fillStyle='#8b7d21';c.fillRect(0,e.h-7,e.w*(1-e.breaches/e.breachLimit),7);if(!e.started){c.fillStyle='rgba(4,6,7,.52)';c.fillRect(0,0,e.w,e.h);c.fillStyle='#f4d729';c.textAlign='center';c.font='900 29px Barlow Condensed, sans-serif';c.fillText('DEFEND THE BASE',e.w/2,e.h*.43);c.fillStyle='#fff';c.font='13px Inter, sans-serif';c.fillText('LEFT / RIGHT to line up · FIRE shoots straight',e.w/2,e.h*.43+28)}if(e.mapBanner>0&&e.started){c.fillStyle='rgba(3,5,6,.72)';c.fillRect(0,e.h*.38,e.w,82);c.fillStyle='#f4d729';c.textAlign='center';c.font='900 27px Barlow Condensed,sans-serif';c.fillText(MAPS[e.mapIndex].name,e.w/2,e.h*.38+34);c.fillStyle='#fff';c.font='11px Inter,sans-serif';c.fillText(`WAVE ${e.wave}`,e.w/2,e.h*.38+55)}}
function drawGround(c,e){const themes=[['#484741','#53524c','#2f2f2b'],['#716046','#7d6c50','#544533'],['#394042','#454d4f','#262b2c'],['#5a5040','#665948','#433a30'],['#4e483d','#5a5447','#383329']];const [base,alt,shade]=themes[e.mapIndex%themes.length];const g=c.createLinearGradient(0,0,0,e.h);g.addColorStop(0,alt);g.addColorStop(.5,base);g.addColorStop(1,alt);c.fillStyle=g;c.fillRect(0,0,e.w,e.h);c.globalAlpha=.14;c.fillStyle='rgba(255,255,255,.06)';for(let y=34;y<e.h;y+=72)c.fillRect(0,y,e.w,2);c.globalAlpha=.11;c.fillStyle=shade;for(let i=0;i<12;i++){const x=(i*97+e.mapIndex*41)%Math.max(60,e.w);const y=(i*53+e.mapIndex*23)%Math.max(40,e.h);c.beginPath();c.ellipse(x,y,34,16,0,0,Math.PI*2);c.fill()}c.globalAlpha=.08;for(let i=0;i<8;i++){const x=((i+1)*e.w)/9;c.fillRect(x,0,1.5,e.h)}c.globalAlpha=1;c.fillStyle='rgba(0,0,0,.08)';c.fillRect(0,0,e.w,e.h)}
function drawPickup(c,p){if(p.blink)return;c.save();c.translate(p.x,p.y);c.shadowBlur=18;c.shadowColor=p.type==='dmr'||p.type==='speed'||p.type==='rapid'?'#f4d729':p.type==='clock'||p.type==='shield'?'#4fb9ff':'#ff4d5e';if(p.type==='heart'){c.fillStyle='#ff4d67';c.font='28px sans-serif';c.textAlign='center';c.fillText('♥',0,9)}else if(p.type==='clock'){c.fillStyle='#52bdff';c.font='25px sans-serif';c.textAlign='center';c.fillText('◷',0,9)}else if(p.type==='speed'){c.fillStyle='#f4d729';c.font='900 18px sans-serif';c.textAlign='center';c.fillText('»',0,6)}else if(p.type==='rapid'){c.fillStyle='#ff9f32';c.font='900 15px sans-serif';c.textAlign='center';c.fillText('RAPID',0,5)}else if(p.type==='shield'){c.strokeStyle='#62d3ff';c.lineWidth=3;c.beginPath();c.arc(0,0,11,0,Math.PI*2);c.stroke()}else if(p.type==='bomb'){c.fillStyle='#0b0b0b';c.strokeStyle='#ffcc39';c.lineWidth=2;c.beginPath();c.arc(0,0,11,0,Math.PI*2);c.fill();c.stroke()}else{c.fillStyle=p.type==='smg'?'#6fe6ff':'#f4d729';c.fillRect(-14,-5,28,10);c.fillStyle='#111';c.fillRect(-4,-9,9,5)}c.restore()}
function hud(){const e=A.engine;if(!e)return;$('#zs52Wave')&&($('#zs52Wave').textContent=e.wave);$('#zs52Remaining')&&($('#zs52Remaining').textContent=Math.max(0,e.waveTarget-e.waveResolved));$('#zs52Score')&&($('#zs52Score').textContent=e.score.toLocaleString());$('#zs52Base')&&($('#zs52Base').textContent=`${e.breaches}/${e.breachLimit}`);$('#zs52Gun')&&($('#zs52Gun').textContent=WEAPONS[e.player.gun].name);$('#zs52Ammo')&&($('#zs52Ammo').textContent=Number.isFinite(e.player.ammo)?e.player.ammo:'∞');$('#zs52Map')&&($('#zs52Map').textContent=MAPS[e.mapIndex].name);$('#zs52Ticker')&&($('#zs52Ticker').textContent=e.ticker);const l=$('#zs52Lives');if(l){const n=e.player.lives,max=e.player.maxLives;l.innerHTML=Array.from({length:max},(_,i)=>{let cls='';if(i<n){cls=max>5&&i<5?'gold':'red'}return `<i class="${cls}">♥</i>`}).join('')}}
async function gameOver(reason){const e=A.engine;if(e.over)return;e.over=true;stopLoop();A.prefs.last=e.score;A.prefs.high=Math.max(A.prefs.high,e.score);savePrefs();e.ticker=reason;await submitScore();A.menu=true;A.tab='menu';renderOverlay();const box=$('.zs52-menu-actions');if(box)box.insertAdjacentHTML('afterbegin',`<div class="zs52-run"><b>RUN COMPLETE</b><span>${e.score.toLocaleString()} points · ${e.kills} kills · Wave ${e.wave}${e.cheated?' · CHEAT RUN':''}</span>${e.cheated?'<small>Cheat runs do not post to the all-time leaderboard.</small>':''}<button class="btn primary" id="zs52Again">Play again</button></div>`);$('#zs52Again')?.addEventListener('click',()=>{A.menu=false;newRun();renderOverlay()})}
async function submitScore(){const e=A.engine;if(e.cheated)return toast('Cheat run complete - leaderboard score not submitted.');const sess=state().session;if(!sess)return toast('Sign in to post your score globally.');let posted=false,firstErr=null;try{const {error}=await deps.supabase.rpc('submit_arcade_run',{p_score:e.score,p_kills:e.kills,p_seconds:Math.max(1,Math.floor(e.elapsed)),p_skin:A.prefs.skin});if(error)throw error;posted=true;}catch(err){firstErr=err;console.warn('submit_arcade_run failed; trying profile fallback',err)}if(!posted){try{const uid=sess.user.id;const cur=await deps.supabase.from('arcade_profiles').select('high_score').eq('user_id',uid).maybeSingle();const best=Math.max(Number(cur.data?.high_score||0),e.score);let q;if(cur.data)q=await deps.supabase.from('arcade_profiles').update({high_score:best,selected_skin:A.prefs.skin}).eq('user_id',uid);else q=await deps.supabase.from('arcade_profiles').insert({user_id:uid,high_score:best,selected_skin:A.prefs.skin,unlocked_skins:A.prefs.codeSkins||[]});if(q.error)throw q.error;posted=true;}catch(err){console.warn('Arcade profile fallback failed',err,firstErr)}}if(posted){A.prefs.high=Math.max(A.prefs.high,e.score);savePrefs();await loadBoard();try{await deps.refreshAll?.()}catch{}toast('Zombie Smash score posted.');}else toast('Score saved locally; online league update failed.');}
function audio(){if(A.audio)return A.audio;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;A.audio=new AC();return A.audio}
function fx(f=440,d=.04){const a=audio();if(!a)return;const o=a.createOscillator(),g=a.createGain();o.type='square';o.frequency.value=f;g.gain.value=.022;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+d);o.stop(a.currentTime+d)}
let music=0,step=0;function startMusic(){if(!A.prefs.music||music)return;const notes=[196,247,294,247,330,294,247,220];music=setInterval(()=>{if(A.open&&!A.paused&&!A.menu)fx(notes[step++%notes.length],.06)},420)}function stopMusic(){clearInterval(music);music=0}
window.ZC2Arcade={init,pageHtml,bindPage,open,close};
})();
